### ISSUE TITLE
It is possible to break totalSupply in a clone and clones that never generate tokens cannot destroy tokens

### ISSUE THREAD

**Issue by ChicoBitcoinJoe** [Giveth/minime#23]
This all stems from `Checkpoint[] totalSupplyHistory;` is never set when a clone is created.

When `generateTokens(...)` is called it retrieves the totalSupply value using the `getValueAt(...)` function. 

We can see that in the `getValueAt(...)` function it will return 0 in the first line if the checkpoint length is 0 (for a new clone it is)

```
function getValueAt(Checkpoint[] storage checkpoints, uint _block
) constant internal returns (uint) {
    if (checkpoints.length == 0) return 0;
    ...
}
```

Now looking back to the `generateToken(...)` function we will see that it then incorrectly sets the totalSupply to 0 + amount

```
if (curTotalSupply + _amount < curTotalSupply) throw(); // Check for overflow
updateValueAtNow(totalSupplyHistory, curTotalSupply + _amount);
```

The simplest fix would be to use `totalSupply()` instead of `getValueAt(...)`.

Additionally, the `destroyTokens(...)` function also uses  `getValueAt(...)` and thus will always throw if a clone attempts to destroy tokens before it has generated tokens (to set the totalSupply checkpoint).

```
uint curTotalSupply = getValueAt(totalSupplyHistory, block.number);
if (curTotalSupply < _amount) revert();
```

This is because curTotalSupply is incorrectly set to 0 by `getValueAt(...)`, 0 is less than the amount we are trying to destroy, and thus it throws.

The simplest fix would be to use `totalSupply()` instead of `getValueAt(...)`.

**Comment by ChicoBitcoinJoe** [comment]
Clone Test showing this behavior

https://ropsten.etherscan.io/address/0xadfcd792f4a83eca6bb67c7f60ac4bd2d42da5ce#code

**Comment by ChicoBitcoinJoe** [comment]
Clone Test Fix showing expected behavior

https://ropsten.etherscan.io/address/0xaaa4e9fa5d308d48ef105338e2890dcb66e0b86e#code

**Comment by ChicoBitcoinJoe** [comment]
The account I used for testing and for checking balances is 0xEC0265063a982f1dBa1Fff8B77Ee1f3DA8cBdbDd.

**Comment by jbaylina** [comment]
You are absolutely right!! 

Just fixed!
